const {
  APP_DOMAIN = '',
  MONGODB_URI = '',
  AUTH0_AUDIENCE = '',
  SUPABASE_PROJECT_URL = '',
  SUPABASE_API_KEY = '',
  DB_SESSION_MODE_URL = '',
  SUPABASE_ACCESS_TOKEN = '',
} = process.env;

export {
  APP_DOMAIN,
  MONGODB_URI,
  AUTH0_AUDIENCE,
  DB_SESSION_MODE_URL,
  SUPABASE_PROJECT_URL,
  SUPABASE_API_KEY,
  SUPABASE_ACCESS_TOKEN,
};
